- name: restart postgresql
  service: name=postgresql state=restarted

- name: reload postgresql
  become: yes
  become_user: postgres
  community.postgresql.postgresql_query:
    db: postgres
    query: SELECT pg_reload_conf()

- name: systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
