---
- include: ../../../shared/account.yml user=cquest  uid=1202
- include: ../../../shared/account.yml user=jocelyn uid=1203
- include: ../../../shared/account.yml user=marc_marc uid=1216

- include: ../../../shared/account.yml user=achetta uid=1236
  when: "'achetta' in group_names"

- include: ../../../shared/account.yml user=apavie uid=1211
  when: "'apavie' in group_names"

- include: ../../../shared/account.yml user=cgiquello uid=1212
  when: "'cgiquello' in group_names"

- include: ../../../shared/account.yml user=cormoran uid=1219
  when: "'cormoran' in group_names"

- include: ../../../shared/account.yml user=davidbgk uid=1251
  when: "'davidbgk' in group_names"

- include: ../../../shared/account.yml user=don-vip uid=1247
  when: "'don-vip' in group_names"

- include: ../../../shared/account.yml user=driss uid=1224
  when: "'driss' in group_names"

- include: ../../../shared/account.yml user=etienne uid=1213
  when: "'etienne' in group_names"

- include: ../../../shared/account.yml user=eloks uid=1214
  when: "'eloks' in group_names"

- include: ../../../shared/account.yml user=famlam uid=1250
  when: "'famlam' in group_names"

- include: ../../../shared/account.yml user=flacombe uid=1246
  when: "'flacombe' in group_names"

- include: ../../../shared/account.yml user=francois2 uid=1221
  when: "'francois2' in group_names"

- include: ../../../shared/account.yml user=fred uid=1205
  when: "'fred' in group_names"

- include: ../../../shared/account.yml user=gileri uid=1311
  when: "'gileri' in group_names"

- include: ../../../shared/account.yml user=guillaumeamat uid=1235
  when: "'guillaumeamat' in group_names"

- include: ../../../shared/account.yml user=gpelloux uid=1237
  when: "'gpelloux' in group_names"

- include: ../../../shared/account.yml user=hamlet uid=1305
  when: "'hamlet' in group_names"

- include: ../../../shared/account.yml user=jacques uid=1306
  when: "'jacques' in group_names"

- include: ../../../shared/account.yml user=jben uid=1206
  when: "'jben' in group_names"

- include: ../../../shared/account.yml user=jgcailton uid=1207
  when: "'jgcailton' in group_names"

- include: ../../../shared/account.yml user=juliep uid=1210
  when: "'juliep' in group_names"

- include: ../../../shared/account.yml user=karl uid=1238
  when: "'karl' in group_names"

- include: ../../../shared/account.yml user=lcombe uid=1215
  when: "'lcombe' in group_names"

- include: ../../../shared/account.yml user=ljbouere uid=1248
  when: "'ljbouere' in group_names"

- include: ../../../shared/account.yml user=mael uid=1218
  when: "'mael' in group_names"

- include: ../../../shared/account.yml user=nlehuby uid=1220
  when: "'nlehuby' in group_names"

- include: ../../../shared/account.yml user=nmoyroud uid=1226
  when: "'nmoyroud' in group_names"

- include: ../../../shared/account.yml user=panieravide uid=1230
  when: "'panieravide' in group_names"

- include: ../../../shared/account.yml user=phyks uid=1233
  when: "'phyks' in group_names"

- include: ../../../shared/account.yml user=pyrog uid=1333
  when: "'pyrog' in group_names"

- include: ../../../shared/account.yml user=redfox uid=1209
  when: "'redfox' in group_names"

- include: ../../../shared/account.yml user=rodolphe uid=1208
  when: "'rodolphe' in group_names"

- include: ../../../shared/account.yml user=rvoirin uid=1308
  when: "'rvoirin' in group_names"

- include: ../../../shared/account.yml user=sly     uid=1209
  when: "'sly' in group_names"

- include: ../../../shared/account.yml user=stephanec uid=1225
  when: "'stephanec' in group_names"

- include: ../../../shared/account.yml user=teslix uid=1222
  when: "'teslix' in group_names"

- include: ../../../shared/account.yml user=thomasg77 uid=1249
  when: "'thomasg77' in group_names"

- include: ../../../shared/account.yml user=thomasl uid=1210
  when: "'thomasl' in group_names"

- include: ../../../shared/account.yml user=thorieux uid=1229
  when: "'thorieux' in group_names"

- include: ../../../shared/account.yml user=thrrp uid=1310
  when: "'thrrp' in group_names"

- include: ../../../shared/account.yml user=tykayn uid=1312
  when: "'tykayn' in group_names"

- include: ../../../shared/account.yml user=tyndare uid=1212
  when: "'tyndare' in group_names"

- include: ../../../shared/account.yml user=vdct uid=1217
  when: "'vdct' in group_names"

- include: ../../../shared/account.yml user=ybon uid=1223
  when: "'ybon' in group_names"

- include: ../../../shared/account.yml user=ydel uid=1313
  when: "'ydel' in group_names"
...
