- name: restart postgresql
  service: name=postgresql state=restarted

- name: restart apache
  service: name=apache2 state=restarted

- name: restart gunicorn
  systemd:
    name: gunicorn-osmose
    state: restarted
    enabled: yes
