- name: configure monit webserver
  template: src=monit-webserver dest=/etc/monit/conf.d/webserver mode=0600 owner=root group=root force=yes
  notify: restart monit

- name: configure monit alert
  template: src="monit-alert" dest="/etc/monit/conf.d/alert" owner=root group=root mode=0644
  notify: restart monit

- name: Fix openssh module to remove dsa key check (patch 1)
  patch:
    src: monit-openssh-no-dsa-check-1.patch
    dest: /etc/monit/conf-available/openssh-server

- name: Fix openssh module to remove dsa key check (patch 2)
  patch:
    src: monit-openssh-no-dsa-check-2.patch
    dest: /etc/monit/conf-available/openssh-server

- name: add monit modules
  file: src="/etc/monit/monitrc.d/{{ item }}" dest="/etc/monit/conf.d/{{ item }}" state=link
  notify: restart monit
  with_items:
    - cron
    - openssh-server
  when: ((ansible_distribution == 'Debian' and ansible_distribution_release == 'jessie') or
         (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int < 17))

- name: add monit modules
  file: src="/etc/monit/conf-available/{{ item }}" dest="/etc/monit/conf-enabled/{{ item }}" state=link
  notify: restart monit
  with_items:
    - cron
    - openssh-server
  when: ((ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 9) or
         (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int == 17))

# apache
- name: add monit module for apache
  copy: src="monit-apache" dest="/etc/monit/conf.d/apache" owner=root group=root mode=0644
  notify: restart monit
  when: install_apache

# munin
- name: add monit module for munin
  copy: src="monit-munin" dest="/etc/monit/conf.d/munin" owner=root group=root mode=0644
  notify: restart monit

# mysql
- name: check if mysql installed
  command: /usr/bin/test -e /var/run/mysqld/mysqld.pid
  ignore_errors: True
  register: mysql_installed

- name: add monit module for mysql
  copy: src="monit-mysql" dest="/etc/monit/conf.d/mysql" owner=root group=root mode=0644
  notify: restart monit
  when: mysql_installed.rc == 0

# postgresql
- name: find version of postgresql
  shell: '/usr/bin/test -e /etc/postgresql/{{ item }}/main && echo "{{ item }}"'
  with_items:
    - 8.4
    - 9.1
    - 9.2
    - 9.3
    - 9.6
    - 10
    - 11
  ignore_errors: True
  register: postgresql_installed

- name: set postgresql_version
  set_fact: postgresql_version="{{ item.stdout }}"
  when: item.rc == 0
  with_items: "{{ postgresql_installed.results }}"
  ignore_errors: True

- name: add monit module for postgresql
  template: src="monit-postgresql" dest="/etc/monit/conf.d/postgresql" owner=root group=root mode=0644
  notify: restart monit
  when: postgresql_version is defined

# sympa
- name: check if sympa installed
  command: /usr/bin/test -e /var/run/sympa/sympa.pid
  ignore_errors: True
  register: sympa_installed

- name: add monit module for sympa
  copy: src="monit-sympa" dest="/etc/monit/conf.d/sympa" owner=root group=root mode=0644
  notify: restart monit
  when: sympa_installed.rc == 0

# apache configuration to access monit
- include: apache2-monit.yml
  when: install_apache
